FROM ubuntu:latest
EXPOSE 3000
RUN mkdir /server
RUN mkdir /server/contents
RUN mkdir /server/images
RUN apt-get update --yes
RUN apt-get install --yes nodejs
RUN apt-get install --yes npm
RUN npm install forever -g
RUN ln -s /usr/bin/nodejs /usr/bin/node
COPY app.js /server/app.js
COPY package.json /server/package.json
WORKDIR /server
RUN npm install
CMD forever -c 'node' app.js